const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  get: (key) => ipcRenderer.invoke('store:get', key),
  getAll: () => ipcRenderer.invoke('store:getAll'),
  set: (obj) => ipcRenderer.invoke('store:set', obj),
  reset: () => ipcRenderer.invoke('store:reset'),
  systemInfo: () => ipcRenderer.invoke('system:info'),
  javaVersion: (p) => ipcRenderer.invoke('system:javaVersion', p),
  javaRequired: (mc) => ipcRenderer.invoke('java:required', mc),
  provisionJava: (mc) => ipcRenderer.invoke('java:provision', mc),
  selectJava: () => ipcRenderer.invoke('dialog:selectJava'),
  selectGameDir: () => ipcRenderer.invoke('dialog:selectGameDir'),
  selectSkin: () => ipcRenderer.invoke('dialog:selectSkin'),
  openFolder: (sub) => ipcRenderer.invoke('folder:open', sub),
  skinsList: () => ipcRenderer.invoke('skins:list'),
  skinsApply: (name) => ipcRenderer.invoke('skins:apply', name),
  skinsDelete: (name) => ipcRenderer.invoke('skins:delete', name),
  modsList: () => ipcRenderer.invoke('mods:list'),
  modsToggle: (name) => ipcRenderer.invoke('mods:toggle', name),
  modsDelete: (name) => ipcRenderer.invoke('mods:delete', name),
  installModrinth: (args) => ipcRenderer.invoke('mods:installModrinth', args),
  allVersions: (args) => ipcRenderer.invoke('versions:all', args),
  fabricVersions: (mc) => ipcRenderer.invoke('versions:fabric', mc),
  quiltVersions: (mc) => ipcRenderer.invoke('versions:quilt', mc),
  forgeVersions: (mc) => ipcRenderer.invoke('versions:forge', mc),
  neoforgeVersions: (mc) => ipcRenderer.invoke('versions:neoforge', mc),
  installForge: (args) => ipcRenderer.invoke('modloader:installForge', args),
  installNeoForge: (args) => ipcRenderer.invoke('modloader:installNeoForge', args),
  launch: (opts) => ipcRenderer.invoke('game:launch', opts),
  isRunning: () => ipcRenderer.invoke('game:isRunning'),
  news: () => ipcRenderer.invoke('news:get'),
  updateCheck: () => ipcRenderer.invoke('update:check'),
  updateApply: () => ipcRenderer.invoke('update:apply'),
  updateOpenPage: () => ipcRenderer.invoke('update:openPage'),
  onLog: (cb) => ipcRenderer.on('launch:log', (_e, msg) => cb(msg)),
  onProgress: (cb) => ipcRenderer.on('launch:progress', (_e, p) => cb(p)),
  onClosed: (cb) => ipcRenderer.on('launch:closed', (_e, code) => cb(code)),
  onStarted: (cb) => ipcRenderer.on('launch:started', () => cb())
});
